name: Clean issues

on:
  workflow_call:

jobs:
  stale:
    name: Clean issues
    runs-on: ubuntu-latest

    steps:
      - name: Clean issues
        uses: actions/stale@v3

        with:
          days-before-stale: 14
          days-before-close: 7
          exempt-issue-labels: "pinned,help wanted,investigating,evaluating"
          stale-issue-message: "This issue is stale because it has been open 14 days with no activity. Remove stale label or comment or this will be closed in 7 days."
